services:
  postgres:
    image: postgres:latest
    container_name: booking-service-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BookingService
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - tutoring-platform-network

networks:
  tutoring-platform-network:
    driver: bridge

volumes:
  tutoring-platform-kafka-data: